version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: chatapp
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3001:${APP_PORT}
    depends_on:
      - db
    profiles:
      - main

  db:
    image: postgres:16.0
    container_name: chatapp_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:${DB_PORT}
    profiles:
      - main

  test-db:
    image: postgres:16.0
    container_name: chatapp_test_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - 5430:${TEST_DB_PORT}
    profiles:
      - test

volumes:
  postgres_data:
